name: Application cron to deploy auto the website

on:
#  push: {}
  workflow_dispatch: {}
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  build-caddy-validator:
    environment: IGP
    env:
      IGP: ${{ secrets.IGP }}
      IGU: ${{ secrets.IGU }}
    name: Agregate and redeploy if necessary
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      # - name: Install python3
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10' 

      # Python patch on ARM64
      - name: Set up Python in a virtual env
        run: |
          sudo apt -y install python3-venv
          python3 -m venv .env
      - name: Install dependencies
        run: |
          source .env/bin/activate
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install the insta DL
        env:
          IGP: ${{ secrets.IGP }}
          IGU: ${{ secrets.IGU }}
        run: pip3 install instaloader
      - name: Add python binaries to path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run the IG agregator
        working-directory: ./agregator
        run: go run plg.go
      - name: Run the tickets agregator
        working-directory: ./agregator/tickets
        run: go run tickets.go
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: 'Update triggered from the GA'
